check-syntax:
	clang -o nul -Wall -S $(CHK_SOURCES)

test:test.c
	clang test.c -o test

addition:addition.c
	clang addition.c -o addition

range:range.c
	clang range.c -o range

char:char.c
	clang char.c -o char

intconst:intconst.c
	clang intconst.c -o intconst

flconst:flconst.c
	clang flconst.c -o flconst

chrconst:chrconst.c
	clang chrconst.c -o chrconst

bell:bell.c
	clang bell.c -o bell

backspace:backspace.c
	clang backspace.c -o backspace

newtab:newtab.c
	clang newtab.c -o newtab

arithmetic:arithmetic.c
	clang arithmetic.c -o arithmetic

bool:bool.c
	clang bool.c -o bool

define:define.c
	clang define.c -o define

complex:complex.c
	clang complex.c -o complex -lm

tildenot:tildenot.c
	clang tildenot.c -o tildenot